version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    groups:
      minor-and-patch:
        update-types: ["minor", "patch"]
    schedule:
      interval: "monthly"
      time: "06:00"
    open-pull-requests-limit: 10
